### ISSUE TITLE
[Bug]: macOS Silicon builds fails to fun

### ISSUE THREAD

**Issue by jacksongoode** [scopeclient/scope#42]
### Describe the bug

Immediately crashes on run

### Steps to reproduce

Download and open the macOS arm build

### Expected behavior

Open or provide some error log

### Operating System and Architecture

macOS Silicon

### Scope Version

Nightly

**Comment by DovidP** [comment]
Chances are none of the builds will work until the oobe is working as you need a .env file to login now. Scope does work on apple silicon. Wait till the oobe is released and if you have issues then you can open an issue.

**Comment by jacksongoode** [comment]
Oh okay no worries. Thanks!
